# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x07peachdb\"\xb8\x01\n\x10\x43reateBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\x11\n\tdocuments\x18\x03 \x03(\t\x12\x1b\n\x0ellm_model_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12!\n\x14\x65mbedding_model_name\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x11\n\x0f_llm_model_nameB\x17\n\x15_embedding_model_name\"#\n\x11\x43reateBotResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\":\n\x19\x43reateConversationRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"G\n\x1a\x43reateConversationResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"U\n\x1b\x43ontinueConversationRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"0\n\x1c\x43ontinueConversationResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x9e\x02\n\nBotService\x12\x44\n\tCreateBot\x12\x19.peachdb.CreateBotRequest\x1a\x1a.peachdb.CreateBotResponse\"\x00\x12\x61\n\x12\x43reateConversation\x12\".peachdb.CreateConversationRequest\x1a#.peachdb.CreateConversationResponse\"\x00\x30\x01\x12g\n\x14\x43ontinueConversation\x12$.peachdb.ContinueConversationRequest\x1a%.peachdb.ContinueConversationResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOTREQUEST._serialized_start=23
  _CREATEBOTREQUEST._serialized_end=207
  _CREATEBOTRESPONSE._serialized_start=209
  _CREATEBOTRESPONSE._serialized_end=244
  _CREATECONVERSATIONREQUEST._serialized_start=246
  _CREATECONVERSATIONREQUEST._serialized_end=304
  _CREATECONVERSATIONRESPONSE._serialized_start=306
  _CREATECONVERSATIONRESPONSE._serialized_end=377
  _CONTINUECONVERSATIONREQUEST._serialized_start=379
  _CONTINUECONVERSATIONREQUEST._serialized_end=464
  _CONTINUECONVERSATIONRESPONSE._serialized_start=466
  _CONTINUECONVERSATIONRESPONSE._serialized_end=514
  _BOTSERVICE._serialized_start=517
  _BOTSERVICE._serialized_end=803
# @@protoc_insertion_point(module_scope)
