# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x07peachdb\"L\n\x10\x43reateBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\x11\n\tdocuments\x18\x03 \x03(\t\"#\n\x11\x43reateBotResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\":\n\x19\x43reateConversationRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"G\n\x1a\x43reateConversationResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\"U\n\x1b\x43ontinueConversationRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"0\n\x1c\x43ontinueConversationResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x9e\x02\n\nBotService\x12\x44\n\tCreateBot\x12\x19.peachdb.CreateBotRequest\x1a\x1a.peachdb.CreateBotResponse\"\x00\x12\x61\n\x12\x43reateConversation\x12\".peachdb.CreateConversationRequest\x1a#.peachdb.CreateConversationResponse\"\x00\x30\x01\x12g\n\x14\x43ontinueConversation\x12$.peachdb.ContinueConversationRequest\x1a%.peachdb.ContinueConversationResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOTREQUEST._serialized_start=22
  _CREATEBOTREQUEST._serialized_end=98
  _CREATEBOTRESPONSE._serialized_start=100
  _CREATEBOTRESPONSE._serialized_end=135
  _CREATECONVERSATIONREQUEST._serialized_start=137
  _CREATECONVERSATIONREQUEST._serialized_end=195
  _CREATECONVERSATIONRESPONSE._serialized_start=197
  _CREATECONVERSATIONRESPONSE._serialized_end=268
  _CONTINUECONVERSATIONREQUEST._serialized_start=270
  _CONTINUECONVERSATIONREQUEST._serialized_end=355
  _CONTINUECONVERSATIONRESPONSE._serialized_start=357
  _CONTINUECONVERSATIONRESPONSE._serialized_end=405
  _BOTSERVICE._serialized_start=408
  _BOTSERVICE._serialized_end=694
# @@protoc_insertion_point(module_scope)
